name: Cypress Tests

on:
  pull_request:
    branches: [main]

jobs:
  cypress:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Start Vite server
        run: npm run dev &

      - name: Wait for Vite server to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          wait-on: http://localhost:3000
        env:
          CI: true
