name: Cypress Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  cypress:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Start Vite server
        run: npm run dev &

      - name: Wait for Vite server to be ready
        uses: jakejarvis/wait-action@v1
        with:
          timeout: 60
          url: http://localhost:3000

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CI: true
